export const CREATE_MEAL_REQUEST = "CREATE_MEAL_REQUEST";
export const CREATE_MEAL_SUCCESS = "CREATE_MEAL_SUCCESS";

export const GET_MEALS_REQUEST = "GET_MEALS_REQUEST";
export const GET_MEALS_SUCCESS = "GET_MEALS_SUCCESS";

export const GET_MEAL_REQUEST = "GET_MEAL_REQUEST";
export const GET_MEAL_SUCCESS = "GET_MEAL_SUCCESS";

export const UPDATE_MEAL_REQUEST = "UPDATE_MEAL_REQUEST";
export const UPDATE_MEAL_SUCCESS = "UPDATE_MEAL_SUCCESS";

export const DELETE_MEAL_REQUEST = "DELETE_MEAL_REQUEST";
export const DELETE_MEAL_SUCCESS = "DELETE_MEAL_SUCCESS";
